on:
  push:
    branches:
      - master
jobs:
  clean_cache:
    runs-on: ubuntu-latest
    needs: workflow
    permissions:
      actions: write
      contents: read
    steps:
      - name: clean_cache
        run: |
          for id in "$(gh cache list | tail -n +2 | awk '{print $1}')"; do
            echo "id" "$id"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}

  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: cache
        uses: actions/cache@v4
        with:
          path: /tmp/github-cache
          key: ${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}

      - run: bash .github/workflows/deploy_frontend.sh '${{ secrets.SA_KEY }}'
      # - run: bash .github/workflows/deploy_backend.sh '${{ secrets.BACKEND_SA_KEY }}' '${{ secrets.SECRETS_JSON }}'
      - run: bash .github/workflows/load_backend_cache.sh
      - run: bash .github/workflows/load_backend_cache.sh

      - name: write cache
        uses: actions/cache/save@v4
        with:
          path: /tmp/github-cache
          key: ${{ steps.cache.outputs.cache-primary-key }}
