on:
  push:
    branches:
      - master
jobs:
  workflow:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_INLINE_CACHE: 1
      CACHE_FROM: type=local,src=/tmp/docker-cache/buildx-cache
      CACHE_TO: type=local,dest=/tmp/docker-cache/buildx-cache,mode=max

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker
          restore-keys: |
            ${{ runner.os }}-docker

      - run: ls -lah /tmp/docker-cache || true

      - run: bash .github/workflows/deploy_frontend.sh '${{ secrets.SA_KEY }}'
      - run: bash .github/workflows/deploy_backend.sh '${{ secrets.BACKEND_SA_KEY }}' '${{ secrets.SECRETS_JSON }}'

      - name: Save Docker image cache
        run: |
          docker save -o /tmp/docker-cache/app.tar first2know:latest

      - name: Cache Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
