on:
  push:
    branches:
      - master
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Restore and load Docker image cache
        run: |
          if [ -f "/tmp/docker-cache/app.tar" ]; then
            docker load -i /tmp/docker-cache/app.tar
            echo "Docker image cache restored and loaded."
          else
            echo "No cache found, building from scratch."
          fi

      - run: bash .github/workflows/deploy_frontend.sh '${{ secrets.SA_KEY }}'
      - run: bash .github/workflows/deploy_backend.sh '${{ secrets.BACKEND_SA_KEY }}' '${{ secrets.SECRETS_JSON }}'

      - name: Save Docker image cache
        run: |
          mkdir -p /tmp/docker-cache
          docker save -o /tmp/docker-cache/app.tar first2know:latest

      - name: Cache Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
