on:
  push:
    branches:
      - master
jobs:
  clean_cache:
    runs-on: ubuntu-latest
    needs: workflow
    permissions:
      actions: write
      contents: read
    steps:
      - name: Cleanup
        run: |
          echo "Fetching list of cache key"
          gh cache --help
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: cache
        uses: actions/cache@v4
        with:
          path: /tmp/github-cache
          key: ${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}

      - run: bash .github/workflows/deploy_frontend.sh '${{ secrets.SA_KEY }}'
      # - run: bash .github/workflows/deploy_backend.sh '${{ secrets.BACKEND_SA_KEY }}' '${{ secrets.SECRETS_JSON }}'
      - run: bash .github/workflows/load_backend_cache.sh
      - run: bash .github/workflows/load_backend_cache.sh

      - name: write cache
        uses: actions/cache/save@v4
        with:
          path: /tmp/github-cache
          key: ${{ steps.cache.outputs.cache-primary-key }}
