on:
  push:
    branches:
      - master
jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: read cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/github-cache
          key: ${{ runner.os }}

      - run: bash .github/workflows/deploy_frontend.sh '${{ secrets.SA_KEY }}'
      # - run: bash .github/workflows/deploy_backend.sh '${{ secrets.BACKEND_SA_KEY }}' '${{ secrets.SECRETS_JSON }}'
      - run: bash .github/workflows/load_backend_cache.sh
      - run: bash .github/workflows/load_backend_cache.sh

      - name: write cache
        uses: actions/cache/save@v4
        with:
          path: /tmp/github-cache
          key: ${{ steps.cache.outputs.cache-primary-key }}
