on:
  push:
    branches:
      - master
jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: cache
        uses: actions/cache@v4
        with:
          path: /tmp/github-cache
          key: ${{ runner.os }}-github

      - run: bash .github/workflows/deploy_frontend.sh '${{ secrets.SA_KEY }}'
      - run: bash .github/workflows/deploy_backend.sh '${{ secrets.BACKEND_SA_KEY }}' '${{ secrets.SECRETS_JSON }}'
      - run: bash .github/workflows/deploy_backend.sh '${{ secrets.BACKEND_SA_KEY }}' '${{ secrets.SECRETS_JSON }}'
